### ISSUE TITLE
correct location for install-config?

### ISSUE THREAD

**Issue by DustinTrap** [RedHatOfficial/ocp4-vsphere-upi-automation#10]
TASK [common : Generate the ignition manifests] *************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["openshift-install", "create", "manifests", "--dir=/ocp/ocp4-vsphere-upi-automation/install-dir"], "delta": "0:00:00.106394", "end": "2020-04-09 14:31:55.273405", "msg": "non-zero return code", "rc": 1, "start": "2020-04-09 14:31:55.167011", "stderr": "level=fatal msg=\"failed to fetch Master Machines: failed to load asset \\\"Install Config\\\": invalid \\\"install-config.yaml\\\" file: pullSecret: Invalid value: \\\"{\\\\\\\"auths\\\\\\\": \\\\\\\"...\\\\\\\"}\\\": json: cannot unmarshal string into Go struct field imagePullSecret.auths of type map[string]map[string]interface {}\"", "stderr_lines": ["level=fatal msg=\"failed to fetch Master Machines: failed to load asset \\\"Install Config\\\": invalid \\\"install-config.yaml\\\" file: pullSecret: Invalid value: \\\"{\\\\\\\"auths\\\\\\\": \\\\\\\"...\\\\\\\"}\\\": json: cannot unmarshal string into Go struct field imagePullSecret.auths of type map[string]map[string]interface {}\""], "stdout": "", "stdout_lines": []}

My install is suffering a fatal error as seen above. I'm executing from the /ocp/ocp4-vsphere-upi-automation directory and my /root/ocp4/install-config.yaml is as per the directions for the helper node. Where does this need to be?

**Comment by vchintal** [comment]
We will be using helper only for all the services (DHCP, DNS, Load Balancer, Web Server, TFTP) it provides but not for installation. As mentioned earlier the only files you need to touch are the `staging`, `group_vars/all.yml` and `ansible.cfg`. In the `group_vars/all.yml`, line 8, you have to get the pull secret from Red Hat and add it as a line. The `install-config.yml` is auto-generated from a template. The link to pull secret is given in the README.

**Comment by DustinTrap** [comment]
Great, that worked. I'm going to make a commit and merge request with some updates to your docs that will hopefully make them easier to read. Thank you!
