### ISSUE TITLE
Accomodate worker vm groups a.k.a MachineConfigPools with custom hardware specs

### ISSUE THREAD

**Issue by ron1** [RedHatOfficial/ocp4-vsphere-upi-automation#13]
It would be useful to define groups of worker vms, i.e., infra, storage, app, etc., at provisioning time. Each of these groups might require its own hardware specs, i.e., memory_mb, num_cpus, etc. Finally, it might be useful to optionally automate the creation of OpenShift MachineConfigPools for these worker_vms subgroups.

If the VMs were defined as traditional Ansible Hosts in an inventory file that belonged to a group bootstrap_vms, master_vms, worker_vms, or a worker_vms subgroup, then it would be easy for deployers to customize host properties on a per-group basis in the inventory. This would also be familiar to OpenShift 3.11 on vSphere users moving to this repo from https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/vmware-ansible.

**Comment by vchintal** [comment]
There is a default MCP for both master and worker created by OpenShift by default, what would be the intention/purpose of creating new ones? I would prefer to keep the repo simple for the default usecase of getting a cluster up on vSphere. 

Externalizing the master/worker HW specs as variables makes sense.

Ansible inventory file includes only the hosts the playbooks need to run tasks on. In our case, we do not (and should not) run anything on CoreOS hosts and hence they won't be part of the inventory file.

@christianh814 Can you share your thoughts on what @ron1 is asking for ?

**Comment by christianh814** [comment]
This sounds like more of a "day 2" task. Which, in my opinion, is beyond the scope of what you, @vchintal , intended.

**Comment by ron1** [comment]
@vchintal Thanks for the prompt reply.

Say I want 3 worker vm pools, one for `infra` nodes, one for `app` nodes, and one for `storage` nodes. This is a common OCP 3.11 configuration. Here, I want to define different cpu/memory variables for each pool.

For nodes in the `storage` pool, I also want to include custom disk configuration to meet OCS 4.3 local storage requirements as described here: https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.3/html-single/deploying_openshift_container_storage/index#requirements-for-installing-openshift-container-storage-using-local-storage-devices_rhocs. This support for `storage` nodes might be similar to that offered by the following repo which appears to be a fork of this one: https://github.com/waynedovey/ocp4-vsphere-upi-automation/blob/3eee1abb2438236dab45417a7a84dd0c4669b259/vars/vars-helpernode-gsslab.yaml#L56.

The primary requirement here is to externalize the worker HW specs. Since the HW specs for VMs within a group/pool are typically the same, I thought it might be convenient to define the groups up front and have them passthrough as MachineConfigPools. In the strictest sense, I guess MachineConfig/Pool updates as described here could be considered "day 2" tasks: https://access.redhat.com/solutions/4342791.

**Comment by vchintal** [comment]
Closing this as any changes to MCP should be done post-install as Day 2 Ops
