### ISSUE TITLE
 vSphere Components - details !!

### ISSUE THREAD

**Issue by krishvoor** [RedHatOfficial/ocp4-vsphere-upi-automation#26]
Team,

Per the looks of it - vSphere is a pretty huge product suite and perhaps has "many components" under it.  
I know for sure we need ESXi, perhaps can you point/document what else would be needed?

**Comment by mallmen** [comment]
You need ESXi and vCenter host for this repository to work from my experience

**Comment by krishvoor** [comment]
@mallmen - Thank you !!

I got lost with those many components under one umbrella - perhaps I believe this needs to be well documented at least somewhere in this repository.

**Comment by vchintal** [comment]
The documentation is more than adequate here: https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation#infrastructure-prerequisites. Please read the README thoroughly when its your first time.
