### ISSUE TITLE
dhcp_ova.yaml fails because of latency=high and no cpu_reservation

### ISSUE THREAD

**Issue by therevoman** [RedHatOfficial/ocp4-vsphere-upi-automation#36]
While running 
`ansible-playbook -i staging dhcp_ova.yml`

The following error occurred with the latest code from main/master.

It appears that govc sets `-latency high` on the vm template, but the ansible module `vmware_guest` is unable to create a VM without specifying a high enough `cpu_reservation`.  Not completely sure though.

TASK [dhcp_ova : Create bootstrap VM from the template] *******************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.vmware.TaskError: ('Invalid CPU reservation for the latency-sensitive VM, (sched.cpu.min) should be at least 8396 MHz. ', None)
failed: [localhost] (item={u'macaddr': u'00:50:56:83:85:6d', u'ipaddr': u'172.16.21.10', u'name': u'bootstrap'}) => {"ansible_loop_var": "item", "changed": false, "item": {"ipaddr": "172.16.21.10", "macaddr": "00:50:56:83:85:6d", "name": "bootstrap"}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1594711610.26-28980-210325313588722/AnsiballZ_vmware_guest.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1594711610.26-28980-210325313588722/AnsiballZ_vmware_guest.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1594711610.26-28980-210325313588722/AnsiballZ_vmware_guest.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_guest', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2834, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2823, in main\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2479, in deploy_vm\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/module_utils/vmware.py\", line 797, in set_vm_power_state\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/module_utils/vmware.py\", line 82, in wait_for_task\n  File \"/tmp/ansible_vmware_guest_payload_2WL_69/ansible_vmware_guest_payload.zip/ansible/module_utils/six/__init__.py\", line 748, in raise_from\nansible.module_utils.vmware.TaskError: ('Invalid CPU reservation for the latency-sensitive VM, (sched.cpu.min) should be at least 8396 MHz. ', None)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by mallmen** [comment]
Hi Nate, I removed '-latency high' from the template upon creation because it causes an issue with memory on the VMs in 4.6.  The IPI installer also uses 'normal' for latency, so this shouldn't be an issue.  Does this also address your issue here?  I hadn't done any testing with the dhcp installs until just recently.

**Comment by ddreggors** [comment]
Resolved
