### ISSUE TITLE
In OCP 4.5 the VMware StorageClass now looks for the infraID not the Cluster Name

### ISSUE THREAD

**Issue by cptmorgan-rh** [RedHatOfficial/ocp4-vsphere-upi-automation#48]
Starting in OCP 4.5 the cloud.conf configuration in the kube-cloud-config configmap now points to /<datacenter>/vm/infraID e.g. "/LAB/vm/openshift-hkzhw"

Currently the playbook creates a folder in VMware using the Cluster name  e.g. "/LAB/vm/openshift". 

This results in a failure when trying to create a PVC using the default StorageClass created by the UPI installer.

I have created the following PR #47 which moves when the fact that is created.

**Comment by mallmen** [comment]
Closed with PR #47
