### ISSUE TITLE
Looking toward 4.6 release, a change with regards ignition spec should be considered

### ISSUE THREAD

**Issue by rdiazgav** [RedHatOfficial/ocp4-vsphere-upi-automation#49]
I guess this it was already considered but just in case, up to 4.5 version the ignition spec is based on spec 2.1.0 but from 4.6 onwards it changes.
Eg: roles/dhcp_ova/templates/append-bootstrap.ign.j2
`{
  "ignition": {
    "config": {
      "merge": [
        {
          "source": "{{ bootstrap_ignition_url }}" 
        }
      ]
    },
    "version": "3.1.0"
  }
}`

I've been using this project to deploy a 4.6 tweaking up the file aforementioned, and I had no issues, either way, this change will not easy as such since it is a conditional change while we have both versions.

thanks!

**Comment by hfenner** [comment]
I ran into headaches provisioning with 4.6.  It's important to note that you need to change both the version from `2.1.0` to `3.1.0`, but also that you change `append` to `merge`.  We can probably write some conditional logic to check for the version of the full bootstrap file and format the append-bootstrap accordingly.

**Comment by JoseRIvera07** [comment]
Hi @hfenner @rdiazgav  is there any other change needed to make this work with 4.6?

I made the changes y'all suggested but I'm still facing the following issue:

TASK [static_ips : Apply patch /ocp4-vsphere-upi-automation/roles/static_ips/files/ocpdev3-bootstrap-0-isolinux.cfg.patch] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 2 out of 2 hunks FAILED
fatal: [localhost]: FAILED! => {"changed": false, "msg": "2 out of 2 hunks FAILED\n"}

**Comment by cgoguyer** [comment]
Hello,
I got the same issue, is there some news about this issue ?

**Comment by mallmen** [comment]
> Hi @hfenner @rdiazgav is there any other change needed to make this work with 4.6?
> 
> I made the changes y'all suggested but I'm still facing the following issue:
> 
> TASK [static_ips : Apply patch /ocp4-vsphere-upi-automation/roles/static_ips/files/ocpdev3-bootstrap-0-isolinux.cfg.patch] *** An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 2 out of 2 hunks FAILED fatal: [localhost]: FAILED! => {"changed": false, "msg": "2 out of 2 hunks FAILED\n"}

Is this still an issue?  Are you actually still installing 4.6 clusters?  There should be no issue with ignition version for currently supported OCP versions.

**Comment by rdiazgav** [comment]
> 

I haven't deployed a cluster using this project for some years, but the last time I did, I can assure you I didn't have any issues, so it was addressed already.
