### ISSUE TITLE
cluster Parameters for VMWARE

### ISSUE THREAD

**Issue by cpitchai** [RedHatOfficial/ocp4-vsphere-upi-automation#60]
Hi Team,

Where we have to introduce the "cluster" parameter for 6.7.

**Comment by mallmen** [comment]
Hi @cpitchai, this is suggesting that if you are running vsphere 6.5 that you may need to set extra parameters for certain Ansible vmware modules.  For example, in this Ansible task file, https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/blob/master/roles/dhcp_ova/tasks/main.yml, `vmware_deploy_ovf` may require you to specify the vmware `cluster` and vmware `resource-pool` when using the module to work properly.  See the Ansible module documentation for details (https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.htmlz)

**Comment by cpitchai** [comment]
Got the Solution
