### ISSUE TITLE
OCP Upgrade

### ISSUE THREAD

**Issue by cpitchai** [RedHatOfficial/ocp4-vsphere-upi-automation#67]
Hi Team,

Do we have any playbook for upgrading the OCP cluster.
Eg: 4.4 to 4.6

**Comment by mallmen** [comment]
Upgrades are pretty simple as is.  I'm not sure I see the benefit of a playbook here.

**Comment by cpitchai** [comment]
For the restricted installation.

**Comment by mallmen** [comment]
Closing as won't fix due to changes in restricted install setups.  `oc-mirror` should be the preferred tool, and it should be managed outside of cluster creation.
