### ISSUE TITLE
VMware folder paths with spaces do not work

### ISSUE THREAD

**Issue by mallmen** [RedHatOfficial/ocp4-vsphere-upi-automation#71]
There are several places where the `vmware.folder_absolute_path` are used in the `command` module which does not work with spaces.  Re-factor the tasks to use `command.argv` to properly handle the spaces.

**Comment by ddreggors** [comment]
I was able to make this work by quoting the path

```
datacenter: 'NPRD Core Server Hosting'
folder_absolute_path: '/NPRD Core Server Hosting/vm/OpenShift/{{ cluster }}'
```

**Comment by ddreggors** [comment]
For what it's worth, the same applies to govc on the command line :-)

**Comment by ddreggors** [comment]
Quoting names with spaces resolve this issue, closing...
