### ISSUE TITLE
Please add a license file to this repo

### ISSUE THREAD

**Issue by dhoeld** [RedHatOfficial/ocp4-vsphere-upi-automation#73]
Hey,

thanks for your amazing work! Can you please add a license file to the repository so others can actually use it?

Thanks!

**Comment by mallmen** [comment]
Hi,

I added a GPL-3.0 license.  I'm not super savvy on the differences, so I'm open to changing it.

Thanks

**Comment by dhoeld** [comment]
Hi @mallmen,

thanks for your response and for adding a license. Do you mind changing the license to a MIT license?

Thanks in advance.
David

**Comment by mallmen** [comment]
Changed to MIT
