### ISSUE TITLE
2 issuse I will put them both in here 

### ISSUE THREAD

**Issue by spazgirl** [RedHatOfficial/ocp4-vsphere-upi-automation#80]
2 issues but I used a work around on the first one and then got stuck on the second one.
it fails here
TASK [vmware : Create the vCenter folder by the same name as the cluster, only if it doesn't exist] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "govc folder.create /Lop_OCP_Datacenter/vm/ocp4-xdfh4", "msg": "[Errno 8] Exec format error: b'govc'", "rc": 8}

So I have to go on tar the file and then comment out the the govc line in all.yml and command out the download and unarchive and make govc excutable lines in pre-install.yml

Environment
OS: rhel 8.4
Ansible Version: 2.9.21-1.el8
OpenShift Version: 4.7
ESXi Version: 7

Commands used to run ansible-playbook
ansible-playbook -vvv -i staging static_ips_ova.yml

Second problem that i am stuck on :  i think it needs mac addresses but how do you get mac addresses for vm's not created yet?

Ansible Playbook Output

see ErrorCreateBootstrap.txt
[ErrorCreateBootstrap.txt](https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/files/6704735/ErrorCreateBootstrap.txt)

Ansible group_vars

[root@x150n151 ocp4-vsphere-upi-automation]# cat group_vars/all.yml
helper_vm_ip: 129.40.80.151
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ignition/bootstrap.ign"
config:
  provider: vsphere
  base_domain: ocphclvmware.com
  cluster_name: ocp4
  fips: false
  isolationMode: NetworkPolicy
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: "{{ lookup('file', '~/pull-secret.json') }}"
vcenter:
  ip: 129.40.80.150
  datastore: OCP_vms_Datastore_Internal
  network: VM Network
  service_account_username: administrator@vsphere.local
  service_account_password: pw4LOPlocalteam!
  admin_username: administrator@vsphere.local
  admin_password: pw4LOPlocalteam!
  datacenter: Lop_OCP_Datacenter
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.13/
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.7/4.7.13/
#  govc: https://github.com/vmware/govmomi/releases/download/v0.26.0/govc_Linux_x86_64.tar.gz
bootstrap_vms:
  - { name: "bootstrap", ipaddr: "129.40.80.157", cpu: 4, ram: 16384}
master_vms:
  - { name: "master0", ipaddr: "129.40.80.152", cpu: 4, ram: 16384}
  - { name: "master1", ipaddr: "129.40.80.153", cpu: 4, ram: 16384}
  - { name: "master2", ipaddr: "129.40.80.154", cpu: 4, ram: 16384}
worker_vms:
  - { name: "worker0", ipaddr: "129.40.80.155", cpu: 4, ram: 16384}
  - { name: "worker1", ipaddr: "129.40.80.156", cpu: 4, ram: 16384}
static_ip:
  gateway: 129.40.80.190
  netmask: 255.255.255.192
  dns: "{{ helper_vm_ip }}"
  network_interface_name: ens192
proxy:
  enabled: false
  http_proxy: http://helper.ocp4.example.com:3129
  https_proxy: http://helper.ocp4.example.com:3129
  no_proxy: example.com
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----
registry:
[ErrorCreateBootstrap.txt](https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/files/6704728/ErrorCreateBootstrap.txt)

  enabled: false
  product_repo: openshift-release-dev
  product_release_name: ocp-release
  product_release_version: 4.4.0-x86_64
  username: ansible
  password: ansible
  email: user@awesome.org
  cert_content:
  host: registry.ocp4.example.com
  port: 5000
  repo: ocp4/openshift4
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
****

**Comment by spazgirl** [comment]
Any status on when this might get looked at?

**Comment by spazgirl** [comment]
So I put the mac addresses that were in the all.yml file back and ran again.  It worked.  So I am gonna assume that since that worked those are what I was suppose to use.  You might want to add a comment saying to just keep those default mac addresses.  Maybe other people just assumed that since they did not have them yet to just leave them as they are default.  Just glad I figured it out.  
But the govc file still stays as tar archived.  I just use the work around that I showed above.  I am sure there is somewhere to change the unzipping the file but I did not change anything else to test it.

**Comment by mallmen** [comment]
Sorry for not replying sooner.  You can define your own mac addresses as long as you follow use the appropriate values corresponding to  appropriate VMware ranges (00:50:56:xx:xx:xx).  The defaults in all.yml fall in the appropriate range.

I will have to do some testing.  The mac address is not a required variable for vmware_guest that creates the VMs.  Maybe that can just be taken out so VMware can auto-generate the mac address.


I'm not sure about the issue with govc.  I have not run a test in a while now.  Does the automation download govc?  You say you have to manually extract it, make it executable, etc.

**Comment by mallmen** [comment]
I am addressing the `macaddr` question here.  For an install using static IP addresses in VMware, you do not need to define the macaddr as VMware will do it for you.  Refactored code to remove requirement to specify the Mac address.  Simply delete it from your `group_vars/all.yml` to allow VMware to auto-generate the MAC addresses for you.  Check the README to see new comments regarding this.

**Comment by mallmen** [comment]
Opened new issue to address your govc issue.

**Comment by spazgirl** [comment]
Thank you,
Teri Wood
