### ISSUE TITLE
task failed

### ISSUE THREAD

**Issue by zengyijian916** [RedHatOfficial/ocp4-vsphere-upi-automation#85]
TASK [common : Display the absolute folder path of the vCenter folder] ***************************
skipping: [localhost]

PLAY [localhost] *********************************************************************************

TASK [vmware : Check if the vCenter folder already exists] ***************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "'govc folder.info /vsphere.com/vm/ocp4-t4kb5'", "msg": "[Errno 2] No such file or directory: b'govc folder.info /vsphere.com/vm/ocp4-t4kb5': b'govc folder.info /vsphere.com/vm/ocp4-t4kb5'", "rc": 2}
...ignoring

TASK [vmware : Create the vCenter folder by the same name as the cluster, only if it doesn't exist] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "'govc folder.create /vsphere.com/vm/ocp4-t4kb5'", "msg": "[Errno 2] No such file or directory: b'govc folder.create /vsphere.com/vm/ocp4-t4kb5': b'govc folder.create /vsphere.com/vm/ocp4-t4kb5'", "rc": 2}

PLAY RECAP ***************************************************************************************
localhost                  : ok=33   changed=12   unreachable=0    failed=1    skipped=12   rescued=0    ignored=1   

[root@Orchestrator upi]#

**Comment by zengyijian916** [comment]
I have changed the task as below:

[root@Orchestrator upi]# cat roles/vmware/tasks/main.yml
  - name: Check if the vCenter folder already exists
    command:
        argv: 
           - govc folder.info {{ vcenter.folder_absolute_path }}
    register: folder_exists
    ignore_errors: yes

  - name: Create the vCenter folder by the same name as the cluster, only if it doesn't exist
    command:
        argv:
         - govc folder.create {{ vcenter.folder_absolute_path }}
    when: folder_exists.rc != 0
[root@Orchestrator upi]# 

and if manually create the folder, this command will successfully.
[root@Orchestrator upi]# govc folder.create /vsphere.com/vm/ocp4-pv8q7

**Comment by ishangaur07** [comment]
Can you explain a little bit more about it

**Comment by mallmen** [comment]
Closing due to no updates from original poster.  I have not heard of issues around folder creation.  Please open a new issue if still having issues.
