### ISSUE TITLE
Only OpenShift versions 4.6.x are worked, higher versions failed 

### ISSUE THREAD

**Issue by johnydo** [RedHatOfficial/ocp4-vsphere-upi-automation#86]
Hi,

the installation with higer versions of OpenShift, tested with 4.7.x and 4.8.x, failed when the core os are patched. What data can i provide to better analyze the problem?

Best regards,
John

**Comment by johnydo** [comment]
Hi,

I use the default configuration in the group_vars/all.yml:

**_download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz_**

But with this files I get this error message:

**_TASK [Apply patch /opt/install/ocp4-vsphere-upi-automation/roles/static_ips/files/bootstrap-isolinux.cfg.patch] ******************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 2 out of 2 hunks FAILED
fatal: [localhost]: FAILED! => {"changed": false, "msg": "2 out of 2 hunks FAILED\n"}_**

**Comment by johnydo** [comment]
Hi,

with this downloads the I get no error messages:

**_download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.45
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.6/4.6.40
  govc: https://github.com/vmware/govmomi/releases/download/v0.24.0/govc_linux_amd64.gz_**

**Comment by vchintal** [comment]
Can you please confirm that you are unable to use the `static_ips_ova.yml` instead of `static_ips.yml` playbook? I am not sure how up-to-date the repo is when it comes to installs via ISO images

**Comment by johnydo** [comment]
Ok, I check this and use the -vvv for more logdetails.

**Comment by johnydo** [comment]
With static_ips_ova.yml the OpenShift cluster are created but at the end of the TASK I get a error message:

**_TASK [static_ips_ova : Create bootstrap VM from the template] 
task path: /opt/install/ocp4-vsphere-upi-automation/roles/static_ips_ova/tasks/main.yml:48_**

**_"msg": "Multiple virtual machines or templates with same name [rhcos-vmware] found."_**

**_PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=45   changed=24   unreachable=0    failed=1    skipped=8    rescued=0    ignored=1_**


I think the problem is the VM rhcos-vmware is not deleted in a previous step? As a work arround can I delete the rhcos-vmware VM after all master and worker VMs are created?

**Comment by johnydo** [comment]
Create, it works with static_ips_ova.yml. Thank you!
