### ISSUE TITLE
Post cluster creation - addition of more worker nodes?

### ISSUE THREAD

**Issue by kcalmond** [RedHatOfficial/ocp4-vsphere-upi-automation#93]
What is the best way to adapt the automation in this repo to **add more worker nodes to a cluster that was created using same automations in this repo**? 

Here's what I tried:
1 - updated and reran the helper node config with info for the new worker nodes.
2 - Added same entries for new worker nodes in group_vars/all.yml. Then ran `ansible-playbook -i staging dhcp_ova.yml` 

Quickly realized that this wasn't going to work. Instead of only processing changes (the Ansible way, right?...) the play started to add another entire cluster from scratch in a new vCenter folder. I killed the play execution and cleaned up. Then started to research how I can add worker nodes to this cluster. No plan on that yet...

**Comment by mallmen** [comment]
I think a new playbook would be needed.  Existing roles could probably be reused or at worst modified slightly to allow for adding new nodes.

**Comment by ddreggors** [comment]
In newer commits we have now added a new_worker_isos.yaml for iso based worker deployment. I will be added a an OVA based solution soon but for now we must generate the iso and add it to a new VM.
